import {
  Activity,
  Airplay,
  AlarmClockIcon,
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  Baby,
  BadgeAlert,
  Bold,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle,
  Settings,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDownUp,
  ChevronsUpDown,
  CircleUserRound,
  Clock,
  Cloud,
  Code,
  Copy,
  Database,
  Ear,
  Fan,
  GalleryHorizontal,
  Github,
  GraduationCap,
  Info,
  Italic,
  Key,
  Lamp,
  LayoutPanelLeft,
  LifeBuoy,
  LogOut,
  type LucideIcon,
  Mail,
  MenuSquare,
  MessageSquare,
  MoonStar,
  Plus,
  PlusCircle,
  Search,
  Sparkles,
  Star,
  Sun,
  Table,
  Terminal,
  Underline,
  UserPlus,
  Users,
  Video,
  Wand2,
  RefreshCw,
  RotateCcw,
  Trash2,
  X,
  Zap,
} from "lucide-react-native";
import {cssInterop} from "nativewind";
function interopIcon(icon: LucideIcon) {
  cssInterop(icon, {
    className: {
      target: "style",
      nativeStyleToProp: {
        color: true,
        opacity: true,
      },
    },
  });
}
interopIcon(Settings);
interopIcon(Sun);
interopIcon(MoonStar);
interopIcon(AlignJustify);
interopIcon(Activity);
interopIcon(Airplay);
interopIcon(AlarmClockIcon);
interopIcon(AlertCircle);
interopIcon(AlignRight);
interopIcon(Baby);
interopIcon(BadgeAlert);
interopIcon(Calendar);
interopIcon(CircleUserRound);
interopIcon(Clock);
interopIcon(Database);
interopIcon(Ear);
interopIcon(Fan);
interopIcon(GalleryHorizontal);
interopIcon(Lamp);
interopIcon(Table);
interopIcon(ArrowDown);
interopIcon(ArrowUp);
interopIcon(ArrowLeft);
interopIcon(ChevronDown);
interopIcon(LayoutPanelLeft);
interopIcon(MenuSquare);
interopIcon(Check);
interopIcon(CheckCircle);
interopIcon(ChevronsDownUp);
interopIcon(ChevronsUpDown);
interopIcon(Copy);
interopIcon(CalendarDays);
interopIcon(Sparkles);
interopIcon(Bold);
interopIcon(Italic);
interopIcon(Underline);
interopIcon(AlignLeft);
interopIcon(Info);
interopIcon(X);
interopIcon(Search);
interopIcon(ChevronRight);
interopIcon(ChevronLeft);
interopIcon(ChevronUp);
interopIcon(Cloud);
interopIcon(LifeBuoy);
interopIcon(LogOut);
interopIcon(Mail);
interopIcon(MessageSquare);
interopIcon(Plus);
interopIcon(PlusCircle);
interopIcon(UserPlus);
interopIcon(Users);
interopIcon(AlignCenter);
interopIcon(Terminal);
interopIcon(AlertTriangle);
interopIcon(Code);
interopIcon(CheckSquare);
interopIcon(Wand2);
interopIcon(RefreshCw);
interopIcon(RotateCcw);
interopIcon(Trash2);
interopIcon(Zap);
interopIcon(Star);
interopIcon(GraduationCap);
interopIcon(Video);
interopIcon(Key);

export {
  Activity,
  Airplay,
  AlarmClockIcon,
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  Baby,
  BadgeAlert,
  Bold,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDownUp,
  ChevronsUpDown,
  CircleUserRound,
  Clock,
  Cloud,
  Code,
  Copy,
  Database,
  Ear,
  Fan,
  GalleryHorizontal,
  Info,
  Italic,
  Key,
  Lamp,
  LayoutPanelLeft,
  LifeBuoy,
  LogOut,
  Settings,
  Mail,
  MenuSquare,
  MessageSquare,
  MoonStar,
  Plus,
  PlusCircle,
  Search,
  Sparkles,
  Star,
  Sun,
  Table,
  Terminal,
  Underline,
  UserPlus,
  Users,
  Video,
  Wand2,
  RefreshCw,
  RotateCcw,
  Trash2,
  X,
  Zap,
};
